name: pdm_lite
channels:
  - defaults
dependencies:
  - ca-certificates
  - libpng
  - python=3.7.16
  - pip
  - pip:
    - torch
    - carla
    - laspy[lazrs,laszip]
    - webcolors
    - ujson
    - scipy
    - rdp
    - h5py
    - gym==0.26.2
    - -r leaderboard/requirements.txt
    - -r scenario_runner/requirements.txt
